export const media = {
  mg1: require("./chuatebongtoi.png"),
  mg2: require("./IsekaiNonbiriNouka.png"),
  mg3: require("./dauphathuongkhung.png"),
  mg4: require("./onepiece.png"),
  mg5: require("./thanhgiumdietquy.png"),
  ab1: require("./1.png"),
  ab2: require("./2.png"),
  ab3: require("./3.png"),
  ab4: require("./4.png"),
  ab5: require("./5.png"),
  bg1: require("./bg2.png"),
  bg2: require("./bg3.png"),
  bg3: require("./bg1.png"),
  bg4: require("./bg4.png"),
  bg5: require("./bg5.png"),
  typel1: require('./typel1.png'),
  typel2: require('./typel2.png'),
  typel3: require('./typel3.png'),
  typel4: require('./typel4.png'),
  typel5: require('./typel5.png'),
  typel6: require('./typel6.png'),
}
